name: MLflow CI - Pima Indians Diabetes

on:
  push:
    branches: [ main ]

jobs:
  train-and-build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up job (Checkout)
        uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow==2.19.0 dagshub pandas numpy scikit-learn matplotlib seaborn joblib

      - name: Set MLflow Tracking URI
        run: |
          echo "MLFLOW_TRACKING_URI=https://dagshub.com/avaiis/Eksperimen_SML_Fara-Katty.mlflow" >> $GITHUB_ENV
          echo "MLFLOW_TRACKING_USERNAME=avaiis" >> $GITHUB_ENV
          echo "MLFLOW_TRACKING_PASSWORD=${{ secrets.DAGSHUB_TOKEN }}" >> $GITHUB_ENV

      - name: Run MLflow project
        env:
          MLFLOW_DISABLE_ENV_CREATION: "true"
        run: |
          # Jalankan mlflow run
          mlflow run MLProject --env-manager=local --experiment-name "Diabetes_Workflow_CI"

      - name: Debug Find mlruns (Cek Lokasi Asli)
        run: |
          echo "Mencari lokasi folder mlruns..."
          find . -name "mlruns" -type d

      - name: Upload artifacts to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: ml-model-artifacts
          # Menggunakan path wildcard agar mencari di root maupun subfolder
          path: "**/mlruns/"
          retention-days: 10

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Model (MLflow Way)
        run: |
          # Cari folder model di mana saja (root atau MLProject)
          MODEL_PATH=$(find . -name "model" -type d | grep "mlruns" | head -n 1)
          echo "Building image from local path: $MODEL_PATH"
          if [ -z "$MODEL_PATH" ]; then echo "MODEL_PATH TIDAK KETEMU!"; exit 1; fi
          mlflow models build-docker -m "$MODEL_PATH" -n "${{ secrets.DOCKERHUB_USERNAME }}/diabetes-model:latest" --install-mlflow

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/diabetes-model:latest

      - name: Complete job
        if: always()
        run: echo "CI job completed successfully"