name: MLflow CI - Pima Indians Diabetes

on:
  push:
    branches: [ main ]

jobs:
  train-and-build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up job
        run: echo "Starting CI/CD Pipeline"

      - name: Run actions/checkout@v3
        uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      - name: Check Env
        run: |
          python --version
          pip --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow==2.19.0 dagshub pandas numpy scikit-learn matplotlib seaborn joblib

      - name: Set MLflow Tracking URI
        run: |
          echo "MLFLOW_TRACKING_URI=https://dagshub.com/avaiis/Eksperimen_SML_Fara-Katty.mlflow" >> $GITHUB_ENV
          echo "MLFLOW_TRACKING_USERNAME=avaiis" >> $GITHUB_ENV
          echo "MLFLOW_TRACKING_PASSWORD=${{ secrets.DAGSHUB_TOKEN }}" >> $GITHUB_ENV

      - name: Run mlflow project
        env:
          MLFLOW_DISABLE_ENV_CREATION: "true"
        run: |
          cd MLProject
          # Jalankan training (Ini akan log ke DagsHub DAN bikin folder online_model)
          python modelling.py
          cd ..

      - name: Get latest Mlflow run_id
        run: |
          # Kita ambil Run ID dari folder mlruns lokal yang otomatis terbuat
          RUN_ID=$(find MLProject/mlruns -maxdepth 2 -type d -name "*-*" | head -n 1 | xargs basename || echo "local_run")
          echo "LATEST_RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Run ID found: $RUN_ID"

      - name: Upload artifacts to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: ml-model-artifacts
          path: MLProject/online_model/
          retention-days: 10

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Model
        run: |
          # PAKAI FOLDER LOKAL (online_model) - Jauh lebih stabil daripada download!
          MODEL_PATH="MLProject/online_model"
          echo "Building Docker image from: $MODEL_PATH"
          mlflow models build-docker -m "$MODEL_PATH" -n "${{ secrets.DOCKERHUB_USERNAME }}/diabetes-model:latest" --install-mlflow

      - name: Tag Docker Image
        run: |
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/diabetes-model:latest ${{ secrets.DOCKERHUB_USERNAME }}/diabetes-model:latest

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/diabetes-model:latest

      - name: Post Log in to Docker Hub
        if: always()
        run: docker logout

      - name: Complete job
        if: always()
        run: echo "CI job completed successfully"