name: MLflow CI - Pima Indians Diabetes

on:
  push:
    branches: [ main ]

jobs:
  train-and-build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up job (Checkout)
        uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow==2.19.0 dagshub pandas numpy scikit-learn matplotlib seaborn joblib

      - name: Set MLflow Tracking URI
        run: |
          echo "MLFLOW_TRACKING_URI=https://dagshub.com/avaiis/Eksperimen_SML_Fara-Katty.mlflow" >> $GITHUB_ENV
          echo "MLFLOW_TRACKING_USERNAME=avaiis" >> $GITHUB_ENV
          echo "MLFLOW_TRACKING_PASSWORD=${{ secrets.DAGSHUB_TOKEN }}" >> $GITHUB_ENV

      - name: Run MLflow project
        env:
          MLFLOW_DISABLE_ENV_CREATION: "true"
        run: |
          # 1. Jalankan training ke DagsHub (Poin Kriteria 3 Basic)
          mlflow run MLProject --env-manager=local --experiment-name "Diabetes_Workflow_CI"
          
          # 2. Masuk ke folder MLProject dulu baru jalankan python, 
          # supaya script bisa menemukan folder 'diabetes_preprocessing'
          cd MLProject
          python modelling.py

          # 3. Pindahkan folder mlruns yang baru terbentuk ke luar agar bisa di-upload
          mv mlruns ../
          cd ..
          
          # Cek folder untuk memastikan
          ls -R mlruns/

      - name: Upload artifacts to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: ml-model-artifacts
          path: "**/mlruns/"
          retention-days: 10

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Model (MLflow Way)
        run: |
          # Cari folder 'model' di mana pun dia berada di dalam mlruns
          MODEL_PATH=$(find . -path "*/mlruns/*/artifacts/model" -type d | head -n 1)
          if [ -z "$MODEL_PATH" ]; then MODEL_PATH=$(find . -name "model" -type d | grep "mlruns" | head -n 1); fi
          
          echo "Building image from local path: $MODEL_PATH"
          mlflow models build-docker -m "$MODEL_PATH" -n "${{ secrets.DOCKERHUB_USERNAME }}/diabetes-model:latest" --install-mlflow

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/diabetes-model:latest

      - name: Complete job
        if: always()
        run: echo "CI job completed successfully"